#!/usr/bin/env node

import { readdir, readFile, writeFile, stat } from 'fs/promises';
import { join, relative, extname } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DOCS_DIR = join(__dirname, '..', 'openxlaw-docs');
const OUTPUT_FILE = join(__dirname, '..', 'openclaw-docs.mdx');

/**
 * Recursively find all markdown files in a directory (excluding zh-CN)
 */
async function findMarkdownFiles(dir, baseDir = dir, fileList = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    
    // Skip zh-CN directory (Chinese translations)
    if (entry.isDirectory() && entry.name === 'zh-CN') {
      continue;
    }
    
    if (entry.isDirectory()) {
      await findMarkdownFiles(fullPath, baseDir, fileList);
    } else if (entry.isFile()) {
      const ext = extname(entry.name);
      if (ext === '.md' || ext === '.mdx') {
        const relativePath = relative(baseDir, fullPath);
        fileList.push({ path: fullPath, relativePath });
      }
    }
  }
  
  return fileList;
}

/**
 * Read file content
 */
async function readFileContent(filePath) {
  try {
    return await readFile(filePath, 'utf-8');
  } catch (error) {
    console.error(`Error reading ${filePath}:`, error.message);
    return `<!-- Error reading file: ${error.message} -->\n`;
  }
}

/**
 * Generate a header for a file section
 */
function generateFileHeader(relativePath) {
  const separator = '='.repeat(80);
  return `\n\n${separator}\n# ${relativePath}\n${separator}\n\n`;
}

/**
 * Main function to merge all documentation files
 */
async function mergeDocs() {
  console.log('Finding all markdown files...');
  const files = await findMarkdownFiles(DOCS_DIR);
  
  // Sort files by their relative path for consistent ordering
  files.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
  
  console.log(`Found ${files.length} files to merge`);
  
  let mergedContent = `# OpenClaw Documentation\n\n`;
  mergedContent += `> This file was automatically generated by merging all English documentation files from the \`openxlaw-docs\` directory.\n`;
  mergedContent += `> Generated on: ${new Date().toISOString()}\n`;
  mergedContent += `> Total files: ${files.length} (English only, excluding zh-CN translations)\n\n`;
  mergedContent += `---\n\n`;
  
  let processedCount = 0;
  
  for (const file of files) {
    console.log(`Processing: ${file.relativePath} (${++processedCount}/${files.length})`);
    
    mergedContent += generateFileHeader(file.relativePath);
    
    const content = await readFileContent(file.path);
    mergedContent += content;
    
    // Add spacing between files
    mergedContent += '\n\n';
  }
  
  console.log(`\nWriting merged documentation to ${OUTPUT_FILE}...`);
  await writeFile(OUTPUT_FILE, mergedContent, 'utf-8');
  
  const stats = await stat(OUTPUT_FILE);
  const fileSizeMB = (stats.size / (1024 * 1024)).toFixed(2);
  
  console.log(`\n✅ Successfully merged ${files.length} files into ${OUTPUT_FILE}`);
  console.log(`   File size: ${fileSizeMB} MB`);
}

// Run the script
mergeDocs().catch((error) => {
  console.error('Error merging documentation:', error);
  process.exit(1);
});
